name: run python demos

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  demos:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.7"]

    steps:
      - name: Shallow clone GLMsingle
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install .
          pip install -r requirements_dev.txt

      - name: Display Python version and packages
        run: |
          python -c "import sys; print(sys.version)"
          pip list

      - name: Run tests and generate coverage report
        run: pytest  --nbmake --nbmake-timeout=3000 "./examples"
