name: MATLAB demos

# Uses the cron schedule for github actions
#
#   will run at 00H00 run on the 1 and 15 of every month
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
#
#         ┌───────────── minute (0 - 59)
#         │ ┌───────────── hour (0 - 23)
#         │ │ ┌───────────── day of the month (1 - 31)
#         │ │ │    ┌───────────── month (1 - 12 or JAN-DEC): * means all
#         │ │ │    │ ┌───────────── day of the week (0 - 6 or SUN-SAT): * means all
#         │ │ │    │ │
#         │ │ │    │ │
#         │ │ │    │ │
# 
# - cron "0 0 1,15 * *"

on:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  demos:
    runs-on: ubuntu-20.04

    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.0.1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Shallow clone GLMsingle
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Run commands
        uses: matlab-actions/run-command@v1.0.1
        with:
          command:
            cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows'));
            run run_demos;
